
import type { Metadata } from 'next'
import { Inter, Bayon, Suwannaphum, Hanuman, Caveat } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

const bayon = Bayon({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bayon",
});

const suwannaphum = Suwannaphum({
  subsets: ["khmer"],
  weight: ["100", "300", "400", "700", "900"], // multiple weights
  variable: "--font-suwannaphum",
});

const hanuman = Hanuman({
  subsets: ["khmer"],
  weight: ["100", "300", "400", "700", "900"], // multiple weights
  variable: "--font-hanuman",
});

const caveat = Caveat({
  subsets: ["latin"],
  weight: ["400", "700"], // multiple weights
  variable: "--font-caveat",
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${bayon.variable} ${suwannaphum.variable} ${hanuman.variable} ${caveat.variable}`}>
      <body className={inter.className}>
        {children}
      </body>
    </html>
  )
}
